### ISSUE TITLE
Update Winston Dependency

### ISSUE THREAD

**Issue by spiderr** [maxcnunes/winston-slackihook#1]
Great module, love it! Any chance on changing the Winston dependency? Winston .9 and 1.0 have many fixes.

**Comment by maxclaus** [comment]
Thanks. I have just published the new version.

**Comment by spiderr** [comment]
Howdy, winston has gone 2.x and the dependency fails fro 1.x. Any chance for expanding the dependency?

Thanks!

**Comment by maxclaus** [comment]
Could you send a pull request please?
